stages:
  - test
  - release

test:
  stage: test
  image: python:$PYTHON_VERSION
  before_script:
    - pip install tox
  script:
    - make test PYTHON=$PYTHON_VERSION
  coverage: /\d+\%\s*$/
  artifacts:
    paths:
      - htmlcov/
  parallel:
    matrix:
      - PYTHON_VERSION:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

upload_to_pypi:
  stage: release
  image: python
  before_script:
    - pip install setuptools wheel twine -U
  script:
    - make build_dist LOCALVERSION=
    - make upload
  when: manual
  only:
    - master
    - /^release/.+$/
    - tags
  environment:
    name: PyPi
    url: https://pypi.org/project/concurrently/
  dependencies: []  # don't fetch artifacts
